{
 "title": "Rest application",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Rest application metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Processing time distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ra_processing_time_total_bucket{le=\"10\"}/ignoring (le) ra_processing_time_total_count",
     "legendFormat": "10"
    },
    {
     "expr": "ra_processing_time_total_bucket{le=\"20\"}/ignoring (le) ra_processing_time_total_count",
     "legendFormat": "20"
    },
    {
     "expr": "ra_processing_time_total_bucket{le=\"40\"}/ignoring (le) ra_processing_time_total_count",
     "legendFormat": "40"
    },
    {
     "expr": "ra_processing_time_total_bucket{le=\"80\"}/ignoring (le) ra_processing_time_total_count",
     "legendFormat": "80"
    },
    {
     "expr": "ra_processing_time_total_bucket{le=\"160\"}/ignoring (le) ra_processing_time_total_count",
     "legendFormat": "160"
    },
    {
     "expr": "ra_processing_time_total_bucket{le=\"320\"}/ignoring (le) ra_processing_time_total_count",
     "legendFormat": "320"
    },
    {
     "expr": "ra_processing_time_total_bucket{le=\"640\"}/ignoring (le) ra_processing_time_total_count",
     "legendFormat": "640"
    },
    {
     "expr": "ra_processing_time_total_bucket{le=\"1280\"}/ignoring (le) ra_processing_time_total_count",
     "legendFormat": "1280"
    },
    {
     "expr": "ra_processing_time_total_bucket{le=\"3000\"}/ignoring (le) ra_processing_time_total_count",
     "legendFormat": "3000"
    },
    {
     "expr": "ra_processing_time_total_bucket{le=\"5000\"}/ignoring (le) ra_processing_time_total_count",
     "legendFormat": "5000"
    },
    {
     "expr": "ra_processing_time_total_bucket{le=\"7500\"}/ignoring (le) ra_processing_time_total_count",
     "legendFormat": "7500"
    },
    {
     "expr": "ra_processing_time_total_bucket{le=\"10000\"}/ignoring (le) ra_processing_time_total_count",
     "legendFormat": "10000"
    },
    {
     "expr": "ra_processing_time_total_bucket{le=\"15000\"}/ignoring (le) ra_processing_time_total_count",
     "legendFormat": "15000"
    },
    {
     "expr": "ra_processing_time_total_bucket{le=\"+Inf\"}/ignoring (le) ra_processing_time_total_count",
     "legendFormat": "+Inf"
    }
   ]
  },
  {
   "title": "Processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(ra_processing_time_total_sum[1m])/rate(ra_processing_time_total_count[1m])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Processing successful/failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(ra_processing_count{status=\"failed\"}[$__rate_interval])",
     "legendFormat": "failed"
    },
    {
     "expr": "rate(ra_processing_count{status=\"success\"}[$__rate_interval])",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Processing invocation rate, requests/second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(ra_processing_endpoint_count[$__rate_interval])",
     "legendFormat": "rate"
    }
   ]
  }
 ]
}